### ISSUE TITLE
Static methods

### ISSUE THREAD

**Issue by vladfaust** [vladfaust/i18n.cr#3]
Why not using Crystal compiler?

```yaml
en:
  foo:
    bar: "baz"
```

```crystal
I18n.backend.load
I18n.generate_static_translations # It's a macro!
I18n.foo.bar("en")
```

However, I don't think it's possible :sweat_smile:
